export const FETCH_CHAT_LIST = 'FETCH_CHAT_LIST'        ////Busca los chats iniciales
export const CHAT_LIST_RECEIVED = 'CHAT_LIST_RECEIVED';
export const CHANGE_CHAT_SELECTED = 'CHANGE_CHAT_SELECTED'
export const PUT_CHAT_ON_TOP_LIST = 'PUT_CHAT_ON_TOP_LIST'

export const FETCH_CHAT_IF_NEED = 'FETCH_CHAT_IF_NEED'
export const FETCH_CHAT = 'FETCH_CHAT'
export const CHAT_RECEIVED = 'CHAT_RECEIVED'
export const PUSH_CHAT_RECEIVED = 'PUSH_CHAT_RECEIVED'
export const PUSH_CHAT_LIST_ELEMENT = 'PUSH_CHAT_LIST_ELEMENT'

export const PUSH_MESSAGE = 'PUSH_MESSAGE'
export const ADD_MESSAGE = 'ADD_MESSAGE'
export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED'
